runtime: python39
service: web
handlers:

  - url: /api/.*
    script: main.app

  # All files that can be compiled in angular. Luckily, they all have suffixes.
  - url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
    static_files: www/\1
    upload: www/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

  # Site root, plus anything else, like deep urls
  # Make this be secure, otherwise oauth redirect won't work if they want to us with http://
  - url: /.*
    static_files: www/index.html
    upload: www/index.html
    secure: always
    expiration: "15m"
